# Generated by Django 3.2 on 2024-07-31 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datamodel',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='image/'),
            preserve_default=False,
        ),
    ]
