# Generated by Django 3.2 on 2024-08-02 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_auto_20240731_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Control_AI_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Develop_Data_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('data', models.DateField()),
                ('image', models.ImageField(upload_to='devevloping/images')),
            ],
        ),
        migrations.RenameModel(
            old_name='Request_Data_Model',
            new_name='Front_Data_Model',
        ),
    ]
