version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: Docker/Django/Dockerfile
    image: aeye_web_back:1.0
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python3.6 manage.py runserver 0.0.0.0:8000
    
  frontend:
    build:
      context: ..
      dockerfile: Docker/Next_js/Dockerfile
    image: ayae_web_front:1.0
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: 
